#!/bin/bash
#check for root
if [ $(id -u) != 0 ]; then
	echo "Run as root."
	exit
fi

ip link set wlan0 up

if [[ $3 != "" ]]; then
	echo "Too many arguments."
	exit
elif [[ $1 != "" && $2 = "" ]]; then
	echo "Need both SSID and password."
	exit
elif [[ $1 != "" && $2 != "" ]]; then
	wpa_passphrase $1 $2 > /tmp/connect.conf
	configFile="/tmp/connect.conf"
else
	configFile="/etc/wpa_supplicant/wpa_supplicant.conf"
fi
wpa_supplicant -i wlan0 -c $configFile -B
sleep 1.5s
udhcpc -i wlan0 -b
ipTest=$(ping -c 1 wtfismyip.com/text 2>&1 /dev/null)

if [[ $ipTest = "ping: unknown host wtfismyip.com/text" ]]; then
	echo "Connection failed."
	disconnect
else
	echo "Connection Succeeded"
	rc-service chronyd start
	rc-service sshd start
	if [[ $configFile = "/tmp/connect.conf" ]]; then
		echo "Save connection?"
		read confirm
		if [[ $confirm == "y" || $confirm == "Y" ]]; then
			cat $configFile >> /etc/wpa_supplicant/wpa_supplicant.conf
		else
			echo "Didn't save."
		fi
	fi
fi
